#! /bin/bash
# este es el interprete que shell va a utilizar

i=0
while IFS=':' read var1 var2 var3 var4 var5 var6 var7
do
    i=$((i + 1))
    echo Registro $i    #$ --> para desreferenciar variables
    echo $var1
    echo $var2
    echo $var3
    echo $var4
    echo $var5
    echo $var6
    echo $var7
done < /etc/passwd

#ejecucion -> chmod +x script --> permisos de ejecucion
# ./script | less  --> less -> para abreviar la direccion del repositorio